"""
“The Brass Head of an Ife Ruler”, a sculptural head of the “royal sculpture” category, from the Yoruba culture of present-day Nigeria, dating to the early 14th-15th century, made of heavily leaded zinc-brass using the lost-wax (cire perdue) technique, with incised markings and traces of red paint, found at the Wunmonije Compound, Ife, and now housed in the British Museum. The head features a crown composed of layered tubular beads, tassels, rosettes and incised plaitwork, small almond-shaped eyes, vertical incised lines on the face, and drilled holes around the lip and jaw. It is thought to represent an Ooni, a ruler of Ife, symbolising royal power and divine kingship. Originally extracted during the era of the Yoruba city-kingdoms in the Late Middle Ages, this object stands as a testament to the sophisticated metallurgical and artistic achievement of the Ife tradition, in which naturalistic form, spiritual symbolism and high-level craftsmanship met. Now displayed in the British Museum, the sculpture offers a rich visual anchor for the relationship of power, ritual and art in historic West Africa.

“The Nautilus Cup”, a luxury object of the “decorative arts” category, created in the mid 16th century, combining a nautilus shell sourced from the Indo-West Pacific with engraved silver-gilt mounts and a chased and gilt marine-themed stand, attributed to European goldsmith work in the Renaissance period and possibly engraved in Guangzhou, China. Made of a nautilus shell mounted in silver-gilt with carved dragons and strapwork, the piece features marine terminal figures, a bird-claw foot, and a richly ornamented mount, demonstrating cross-cultural exchange of material, form and luxury. The object is inscribed with decorative motifs rather than a formal inscription, but its provenance connects the seas of Southeast Asia and the workshops of Europe in the 1500s. Extracted during the era of European overseas trade and court collecting, this ornate cup now resides in the British Museum as part of the Waddesdon Bequest, offering a vivid exemplar of the interplay of natural treasure, artisan technique and elite display.

“The Pressburg Cup”, a standing silver-gilt cup of the “ceremonial silverware” category, originating in Pressburg (modern Bratislava, Slovakia) around c. 1600, made of silver-gilt and engraved with a Hebrew inscription around the lip that records its ownership by the Burial Society of the Jewish community in Pressburg in 1739-40. The cup’s body is chased and engraved with elaborate ornament, and it carries assay and maker’s marks (Nuremberg origin 1600-1700, ram’s head punch of Hans Petzolt). It was created in a context of Renaissance/early Baroque silver production, extracted during the early modern era of civic fraternities and material culture of memory, and is now part of the British Museum’s collection. Through its materials, inscription and ownership history, the cup ties together religious community practice, silver‐working artistry and the circulation of objects across Central Europe.

“The Lothair Crystal”, a carved rock-crystal disc of the “gem-engraving” category, made in the Carolingian Empire (mid-9th century) and later mounted in a 15th-century gilt-copper frame, originally from what is now the Meuse region of northwest Europe. The disc of clear quartz is intaglio-engraved with eight scenes from the biblical story of Susanna and the Elders, accompanied by Latin inscriptions. The work bears the inscription “LOTHARIVS REX FRANCORVM ME FIERI IVSSIT” (Lothair, King of the Franks, ordered me to be made). Created during the era of Carolingian court art and ecclesiastical patronage, the object was later re-mounted in medieval frame. It now resides in the British Museum, where it represents the layered history of gem-engraving, royal ideology and devotional culture across centuries.

“The Casket with Amber Plaques”, a “decorative casket” category object, composed of late 16th- to early 17th-century amber intaglio plaques (probably German, attributed to Königsberg or Augsburg) mounted in silver-gilt mounts (lock, hinge, carcass) made in the second half of the 19th century (probably Parisian workshop), containing scenes of recumbent female figures in landscapes carved on the reverse of the amber plaques. The casket bears no specific inscription, but its decorative programme, combining amber veneer and silver-gilt mounts, reflects the luxury taste and material adaptation of the era of extraction, when older baroque plaques were re-worked in the 19th century for new elite display. Housed in the British Museum as part of the Waddesdon Bequest, this object joins natural material, historic intaglio carving and later mounting in a layered material history.
"""